DROP DATABASE IF EXISTS `testDB`;
CREATE DATABASE `testDB`;

USE testDB;
DROP TABLE IF EXISTS `ID_info`;
CREATE TABLE `ID_info` (
	`ID` VARCHAR(20) NOT NULL ,
	`PW` VARCHAR(255) NOT NULL ,
	`NICKNAME` VARCHAR(20) NOT NULL,
	`RECOREDE_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `USER_info`;
CREATE TABLE `USER_info` (
	`ID` VARCHAR(20) NOT NULL,
	`NICKNAME` VARCHAR(20) NOT NULL,
	`SCORE` INT NOT NULL DEFAULT 0,
	`STAGE` INT NOT NULL DEFAULT 0,
	`RECOREDE_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `CLEARED_STAGE`;
CREATE TABLE `CLEARED_STAGE` (
    `NICKNAME` VARCHAR(20) NOT NULL,
    `ANSWER` INT NOT NULL    
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `LAB_SCORE`;
CREATE TABLE `LAB_SCORE` (
	`ID` INT NOT NULL,
	`SCORE` INT NOT NULL 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `LAB_SCORE` (ID, SCORE) SELECT ID, CASE WHEN ID BETWEEN 1 AND 10 THEN 10 WHEN ID BETWEEN 11 AND 20 THEN 20 WHEN ID BETWEEN 21 AND 30 THEN 30 WHEN ID BETWEEN 31 AND 40 THEN 40 END AS SCORE FROM ( SELECT n AS ID FROM ( SELECT 1 AS n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25 UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30 UNION SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34 UNION SELECT 35 UNION SELECT 36 UNION SELECT 37 UNION SELECT 38 UNION SELECT 39 UNION SELECT 40 ) AS numbers ) AS ids;

CREATE USER `admin`@`localhost` identified by 'flamerootpassword';
GRANT ALL PRIVILEGES ON *.* TO 'admin'@'localhost';

FLUSH PRIVILEGES;