-- 데이터베이스 생성
DROP DATABASE IF EXISTS `flameDB`;
CREATE DATABASE `flameDB`;

USE flameDB;

-- 테이블 생성
DROP TABLE IF EXISTS `ID_info`;
CREATE TABLE `ID_info` (
    `ID` VARCHAR(20) NOT NULL,
    `PW` VARCHAR(255) NOT NULL,
    `NICKNAME` VARCHAR(20) NOT NULL,
    `RECOREDE_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `USER_info`;
CREATE TABLE `USER_info` (
    `ID` VARCHAR(20) NOT NULL,
    `NICKNAME` VARCHAR(20) NOT NULL,
    `SCORE` INT NOT NULL DEFAULT 0,
    `STAGE` INT NOT NULL DEFAULT 0,
    `RECOREDE_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `CLEARED_STAGE`;
CREATE TABLE `CLEARED_STAGE` (
    `NICKNAME` VARCHAR(20) NOT NULL,
    `ANSWER` INT NOT NULL    
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `LAB_SCORE`;
CREATE TABLE `LAB_SCORE` (
    `ID` INT NOT NULL,
    `SCORE` INT NOT NULL 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP DATABASE IF EXISTS `userDB`;
CREATE DATABASE `userDB`;
USE userDB;

DROP TABLE IF EXISTS `flame`;
CREATE TABLE `flame` (
    `NICKNAME` VARCHAR(50) NOT NULL,
    `FLAG` VARCHAR(100) NOT NULL 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `admin`;
CREATE TABLE `admin` (
    `NICKNAME` VARCHAR(50) NOT NULL,
    `FLAG` VARCHAR(100) NOT NULL 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
