services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./Web:/var/www/html:rw
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=flameDB
    networks:
      - app-network

  db:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - ./setup_script/flameDB.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    networks:
      - app-network

  shell:
    build: 
      context: .
      dockerfile: Dockerfile.shell
    volumes:
      - ./setup_script:/setup_script:rw
    privileged: true
    networks:
      - app-network

volumes:
  db_data:
    driver: local

networks:
  app-network:
    driver: bridge
